//! Per-profile Claude Code CLI wrappers.
//!
//! Each profile with `surfaces.cli == true` gets a bash script installed at
//! `~/.local/bin/claude-<slug>`. The script exports `CLAUDE_CONFIG_DIR` to
//! the profile's `cli-config/` directory and execs the real `claude` binary.
//!
//! ## How auth isolation works on macOS
//!
//! On macOS Claude Code stores OAuth credentials in the macOS Keychain rather
//! than a file (unlike Linux/Windows where credentials live in
//! `<CLAUDE_CONFIG_DIR>/.credentials.json`). The Keychain service name is
//! `Claude Code-credentials-<hash>` where `<hash>` is the first 8 hex chars
//! of `SHA-256(CLAUDE_CONFIG_DIR)`. So setting a different `CLAUDE_CONFIG_DIR`
//! per wrapper gives each profile its own Keychain entry automatically.
//!
//! This SHA-256 derivation is undocumented Anthropic internals (verified by
//! reverse-engineering Claude Code's internal `V51()` function; relied upon
//! by community tools like diranged/claude-profile and the KMJ-007 gist).
//! If a future Claude Code release changes the hashing scheme, profile
//! isolation silently breaks. The README must surface this risk.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use crate::error::{AppError, AppResult};
use crate::paths::{cli_config_dir, local_bin_dir};
use crate::profiles::Profile;

/// Marker comment used to identify wrappers generated by claude-profiles.
/// `generate` refuses to overwrite — and `remove` refuses to delete — any
/// file at `~/.local/bin/claude-<slug>` that does not contain this string.
pub const MARKER: &str = "# claude-profiles wrapper";

/// Pure: build the bash script body for a wrapper.
/// `cli_config_path` is the absolute, fully-resolved path that
/// `CLAUDE_CONFIG_DIR` will be set to.
pub fn wrapper_script(profile: &Profile, cli_config_path: &Path) -> String {
    format!(
        r#"#!/bin/bash
{marker} — profile: {name} ({id})
export CLAUDE_CONFIG_DIR="{path}"
exec claude "$@"
"#,
        marker = MARKER,
        name = profile.name,
        id = profile.id,
        path = cli_config_path.display(),
    )
}

/// Build the wrapper for `profile`, install it at `~/.local/bin/claude-<slug>`,
/// chmod 755. Idempotent over wrappers we own; refuses to overwrite anything
/// else (see `MARKER`). Returns the path to the installed wrapper.
pub fn generate(profile: &Profile) -> AppResult<PathBuf> {
    let bin_dir = local_bin_dir()?;
    let config_dir = cli_config_dir(&profile.id)?;
    generate_at(profile, &bin_dir, &config_dir)
}

/// Test-friendly variant of `generate` that takes the bin dir and the
/// per-profile cli-config dir explicitly so unit tests can use a tempdir.
pub fn generate_at(profile: &Profile, bin_dir: &Path, cli_config: &Path) -> AppResult<PathBuf> {
    fs::create_dir_all(bin_dir)?;
    let wrapper_path = bin_dir.join(format!("claude-{}", profile.slug));

    if wrapper_path.exists() {
        let existing = fs::read_to_string(&wrapper_path)?;
        if !existing.contains(MARKER) {
            return Err(AppError::Validation(format!(
                "{} already exists and was not created by claude-profiles; refusing to overwrite",
                wrapper_path.display()
            )));
        }
    }

    let body = wrapper_script(profile, cli_config);
    fs::write(&wrapper_path, body)?;
    let mut perms = fs::metadata(&wrapper_path)?.permissions();
    perms.set_mode(0o755);
    fs::set_permissions(&wrapper_path, perms)?;

    Ok(wrapper_path)
}

/// Remove the wrapper at `~/.local/bin/claude-<slug>`. No-ops if absent.
/// Refuses to delete anything that doesn't carry our marker.
pub fn remove(slug: &str) -> AppResult<()> {
    let bin_dir = local_bin_dir()?;
    remove_at(slug, &bin_dir)
}

pub fn remove_at(slug: &str, bin_dir: &Path) -> AppResult<()> {
    let wrapper_path = bin_dir.join(format!("claude-{slug}"));
    if !wrapper_path.exists() {
        return Ok(());
    }
    let existing = fs::read_to_string(&wrapper_path)?;
    if !existing.contains(MARKER) {
        return Err(AppError::Validation(format!(
            "{} is not a claude-profiles wrapper; refusing to delete",
            wrapper_path.display()
        )));
    }
    fs::remove_file(&wrapper_path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::profiles::Surfaces;
    use std::path::PathBuf;

    fn fixture() -> Profile {
        Profile {
            id: "deadbeef-0000-0000-0000-000000000000".into(),
            name: "Personal".into(),
            slug: "personal".into(),
            color: "#7C3AED".into(),
            created_at: "2026-05-20T12:00:00Z".into(),
            surfaces: Surfaces {
                gui: false,
                cli: true,
            },
        }
    }

    #[test]
    fn script_starts_with_bash_shebang() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        assert!(script.starts_with("#!/bin/bash\n"));
    }

    #[test]
    fn script_includes_marker_comment() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        assert!(script.contains(MARKER));
    }

    #[test]
    fn script_includes_profile_name_and_id_in_header() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        assert!(script.contains("profile: Personal (deadbeef-0000-0000-0000-000000000000)"));
    }

    #[test]
    fn script_exports_claude_config_dir_with_absolute_path() {
        let script = wrapper_script(
            &fixture(),
            &PathBuf::from(
                "/Users/u/Library/Application Support/claude-profiles/profiles/deadbeef/cli-config",
            ),
        );
        assert!(script.contains(
            r#"export CLAUDE_CONFIG_DIR="/Users/u/Library/Application Support/claude-profiles/profiles/deadbeef/cli-config""#
        ));
    }

    #[test]
    fn script_ends_with_exec_claude() {
        let script = wrapper_script(&fixture(), &PathBuf::from("/Users/u/cli-config"));
        let trimmed = script.trim_end();
        assert!(trimmed.ends_with(r#"exec claude "$@""#));
    }

    use crate::error::AppError;
    use std::fs;
    use std::os::unix::fs::PermissionsExt;
    use tempfile::tempdir;

    #[test]
    fn generate_at_creates_executable_wrapper() {
        let bin = tempdir().unwrap();
        let cfg = tempdir().unwrap();
        let profile = fixture();
        let path = generate_at(&profile, bin.path(), cfg.path()).unwrap();

        assert!(path.is_file());
        let body = fs::read_to_string(&path).unwrap();
        assert!(body.contains(MARKER));
        let expected_export = format!("CLAUDE_CONFIG_DIR=\"{}\"", cfg.path().display());
        assert!(body.contains(&expected_export), "body was: {body}");

        let mode = fs::metadata(&path).unwrap().permissions().mode();
        assert_eq!(
            mode & 0o111,
            0o111,
            "wrapper must be user/group/world executable"
        );
    }

    #[test]
    fn generate_at_is_idempotent_over_its_own_wrappers() {
        let bin = tempdir().unwrap();
        let cfg = tempdir().unwrap();
        let profile = fixture();
        let first = generate_at(&profile, bin.path(), cfg.path()).unwrap();
        let second = generate_at(&profile, bin.path(), cfg.path()).unwrap();
        assert_eq!(first, second);
    }

    #[test]
    fn generate_at_refuses_to_overwrite_unmarked_file() {
        let bin = tempdir().unwrap();
        let cfg = tempdir().unwrap();
        let profile = fixture();
        let target = bin.path().join(format!("claude-{}", profile.slug));
        fs::write(&target, "#!/bin/bash\necho hi\n").unwrap();

        let err = generate_at(&profile, bin.path(), cfg.path()).unwrap_err();
        match err {
            AppError::Validation(msg) => assert!(msg.contains("refusing to overwrite")),
            other => panic!("expected Validation error, got {other:?}"),
        }

        let body = fs::read_to_string(&target).unwrap();
        assert_eq!(body, "#!/bin/bash\necho hi\n");
    }

    #[test]
    fn remove_at_is_a_noop_for_missing_files() {
        let bin = tempdir().unwrap();
        remove_at("does-not-exist", bin.path()).unwrap();
    }

    #[test]
    fn remove_at_deletes_a_wrapper_it_owns() {
        let bin = tempdir().unwrap();
        let cfg = tempdir().unwrap();
        let profile = fixture();
        let path = generate_at(&profile, bin.path(), cfg.path()).unwrap();
        assert!(path.exists());

        remove_at(&profile.slug, bin.path()).unwrap();
        assert!(!path.exists());
    }

    #[test]
    fn remove_at_refuses_to_delete_unmarked_files() {
        let bin = tempdir().unwrap();
        let target = bin.path().join("claude-foreign");
        fs::write(&target, "#!/bin/bash\nrm -rf /\n").unwrap();

        let err = remove_at("foreign", bin.path()).unwrap_err();
        match err {
            AppError::Validation(msg) => assert!(msg.contains("refusing to delete")),
            other => panic!("expected Validation error, got {other:?}"),
        }
        assert!(target.exists());
    }
}
